version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
      container_name: foodgram-backend
      image: bauklu/foodgram_backend
      env_file: ../.env
      volumes:
      #  - static:/app/static
        - static:/app/collected_static
        - media:/app/media
        - /home/yc-user/taski/data:/app/data
      command: >
        sh -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 foodgram.wsgi"
  frontend:
    container_name: foodgram-front
    image: bauklu/foodgram_frontend
    env_file: ../.env
    # command: cp -r /app/result_build/. /static/
    volumes:
    #  - ../frontend/:/app/result_build/
    #  - ../frontend/build:/usr/share/nginx/html/
    #  - static:/static
      - ../frontend/build:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
